# These are supported funding model platforms
github: kimtony123
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom: ['https://permaclaw.dev/donate']   # optional, if you have a crypto donation page
